from django.urls import path, include
from . import api_views

urlpatterns = [
    path('categories/', api_views.category_list),
    path('categories/<int:pk>/', api_views.category_detail),
    path('categories/search/<str:phrase>/', api_views.category_search_by_name),
    path('categories/update/<int:pk>/', api_views.category_update_delete),
    path('categories/delete/<int:pk>/', api_views.category_update_delete),
    path('categories/create/', api_views.category_create),
    path('topics/', api_views.topic_list),
    path('topics/<int:pk>/', api_views.topic_detail),
    path('topics/search/<str:phrase>/', api_views.topic_search_by_name),
    path('topicscategories/search/<str:phrase>/', api_views.topic_and_category_search_by_name),
    path('topics/update/<int:pk>/', api_views.topic_update_delete),
    path('topics/delete/<int:pk>/', api_views.topic_update_delete),
    path('topics/create/', api_views.topic_create),
    path('tags/', api_views.tag_list),
    path('tags/<int:pk>/', api_views.tag_detail),
    path('tags/search/<str:phrase>/', api_views.tag_search_by_name),
    path('tags/update/<int:pk>/', api_views.tag_update_delete),
    path('tags/delete/<int:pk>/', api_views.tag_update_delete),
    path('tags/create/', api_views.tag_create),
    path('posts/', api_views.post_list),
    path('posts/<int:pk>/', api_views.post_detail),
    path('posts/search/<str:phrase>/', api_views.post_search_by_name),
    path('posts/update/<int:pk>/', api_views.post_update_delete),
    path('posts/delete/<int:pk>/', api_views.post_update_delete),
    path('posts/create/', api_views.post_create),
    path('pages/', api_views.page_list),
    path('pages/<int:pk>/', api_views.page_detail),
    path('pages/search/<str:phrase>/', api_views.page_search_by_name),
    path('pages/update/<int:pk>/', api_views.page_update_delete),
    path('pages/delete/<int:pk>/', api_views.page_update_delete),
    path('pages/create/', api_views.page_create),
    path('user/posts/', api_views.user_post_list),
]